name: Publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'bifrost-*'
      - 'fix-issues-4931'
    tags:
      - 'v*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: odanado/go-ipfs-test
      WIP_IMAGE_TAG: wip
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build wip Docker image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          context: .
          file: ./Dockerfile
          tags: |
            "${{ env.IMAGE_NAME }}:${{ env.WIP_IMAGE_TAG }}"


      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Docker Image to Docker Hub
        run: ./bin/push-docker-tags.sh $(date -u +%F)

